import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    {
      type: 'category',
      label: 'Choose a Path',
      collapsed: false,
      items: [
        'getting-started/create-react-on-rails-app',
        'getting-started/installation-into-an-existing-rails-app',
        'getting-started/oss-vs-pro',
        'pro/upgrading-to-pro',
        'migrating/migrating-from-react-rails',
        'migrating/migrating-from-vite-rails',
      ],
    },
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', title: 'Getting Started'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: {type: 'generated-index', title: 'Core Concepts'},
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Building Features',
      link: {type: 'generated-index', title: 'Building Features'},
      items: [{type: 'autogenerated', dirName: 'building-features'}],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Upgrading',
      items: [
        {
          type: 'link',
          label: 'Full Changelog (GitHub)',
          href: 'https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md',
        },
        {
          type: 'category',
          label: 'Release Notes',
          items: [{type: 'autogenerated', dirName: 'upgrading/release-notes'}],
        },
        'upgrading/upgrading-react-on-rails',
      ],
    },
    {
      type: 'category',
      label: 'Migrating',
      items: [{type: 'autogenerated', dirName: 'migrating'}],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
    {
      type: 'category',
      label: 'Historical Reference',
      link: {type: 'generated-index', title: 'Historical Reference'},
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
    {
      type: 'category',
      label: 'React on Rails Pro',
      link: {type: 'doc', id: 'pro/react-on-rails-pro'},
      items: [{type: 'autogenerated', dirName: 'pro'}],
    },
  ],
};

export default sidebars;
