import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', title: 'Getting Started'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: {type: 'generated-index', title: 'Core Concepts'},
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Building Features',
      link: {type: 'generated-index', title: 'Building Features'},
      items: [{type: 'autogenerated', dirName: 'building-features'}],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Upgrading',
      items: [{type: 'autogenerated', dirName: 'upgrading'}],
    },
    {
      type: 'category',
      label: 'Migrating',
      items: [{type: 'autogenerated', dirName: 'migrating'}],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
    {
      type: 'category',
      label: 'Pro',
      items: [{type: 'autogenerated', dirName: 'pro'}],
    },
  ],
};

export default sidebars;
